version: '3'

services:
 rabbitmq_service:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./container/rmq:/data
    networks:
      - backend

networks:
  backend:
    driver: bridge
    external: true