version: '3'

services:
  db:
    container_name: "ripbacke_db_1"
    image: postgres
    volumes:
      - ./container/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=host
      - POSTGRES_USER=host
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5000:5000'
    networks:
      - backend

  server:
    build: .
    ports:
      - '3080:3080'
    command: ["npm", "start"]
    depends_on:
      - db
    links:
      - db    
    networks:
      - backend

#  rabbitmq_service:
#    image: "rabbitmq:3-management"
#    container_name: "rabbitmq"
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    volumes:
#      - ./container/rmq:/data

networks:
  backend:
    driver: bridge
    external: true